generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ItemConcurso
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          item_concurso
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, concurso, item, acronimo_recurso, monto_maximo, porcentaje_maximo]
      filter:  ~
      form:    ~ 
      edit:    ~
      new:     ~
