<?php

/**
 * BaseTipoArchivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_documento
 * @property string $acronimo
 * @property Doctrine_Collection $Concursos
 * @property Doctrine_Collection $ConcursoTipoArhivos
 * @property Doctrine_Collection $Archivos
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getNombreDocumento()     Returns the current record's "nombre_documento" value
 * @method string              getAcronimo()            Returns the current record's "acronimo" value
 * @method Doctrine_Collection getConcursos()           Returns the current record's "Concursos" collection
 * @method Doctrine_Collection getConcursoTipoArhivos() Returns the current record's "ConcursoTipoArhivos" collection
 * @method Doctrine_Collection getArchivos()            Returns the current record's "Archivos" collection
 * @method TipoArchivo         setId()                  Sets the current record's "id" value
 * @method TipoArchivo         setNombreDocumento()     Sets the current record's "nombre_documento" value
 * @method TipoArchivo         setAcronimo()            Sets the current record's "acronimo" value
 * @method TipoArchivo         setConcursos()           Sets the current record's "Concursos" collection
 * @method TipoArchivo         setConcursoTipoArhivos() Sets the current record's "ConcursoTipoArhivos" collection
 * @method TipoArchivo         setArchivos()            Sets the current record's "Archivos" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoArchivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_archivo');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre_documento', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('acronimo', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Concurso as Concursos', array(
             'refClass' => 'ConcursoTipoArchivo',
             'local' => 'tipo_archivo_id',
             'foreign' => 'concurso_id'));

        $this->hasMany('ConcursoTipoArchivo as ConcursoTipoArhivos', array(
             'local' => 'id',
             'foreign' => 'tipo_archivo_id'));

        $this->hasMany('ArchivoPostulacion as Archivos', array(
             'local' => 'id',
             'foreign' => 'id_tipo_archivo'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}