<?php

/**
 * BaseAjusteRecurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $evaluacion_id
 * @property integer $recurso_id
 * @property integer $monto_aprobado
 * @property string $comentario
 * @property Evaluacion $Evaluacion
 * @property Recurso $Recurso
 * @property Doctrine_Collection $AjustesDetalleRecurso
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getEvaluacionId()          Returns the current record's "evaluacion_id" value
 * @method integer             getRecursoId()             Returns the current record's "recurso_id" value
 * @method integer             getMontoAprobado()         Returns the current record's "monto_aprobado" value
 * @method string              getComentario()            Returns the current record's "comentario" value
 * @method Evaluacion          getEvaluacion()            Returns the current record's "Evaluacion" value
 * @method Recurso             getRecurso()               Returns the current record's "Recurso" value
 * @method Doctrine_Collection getAjustesDetalleRecurso() Returns the current record's "AjustesDetalleRecurso" collection
 * @method AjusteRecurso       setId()                    Sets the current record's "id" value
 * @method AjusteRecurso       setEvaluacionId()          Sets the current record's "evaluacion_id" value
 * @method AjusteRecurso       setRecursoId()             Sets the current record's "recurso_id" value
 * @method AjusteRecurso       setMontoAprobado()         Sets the current record's "monto_aprobado" value
 * @method AjusteRecurso       setComentario()            Sets the current record's "comentario" value
 * @method AjusteRecurso       setEvaluacion()            Sets the current record's "Evaluacion" value
 * @method AjusteRecurso       setRecurso()               Sets the current record's "Recurso" value
 * @method AjusteRecurso       setAjustesDetalleRecurso() Sets the current record's "AjustesDetalleRecurso" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAjusteRecurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ajuste_recurso');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('evaluacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('recurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('monto_aprobado', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('comentario', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Evaluacion', array(
             'local' => 'evaluacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Recurso', array(
             'local' => 'recurso_id',
             'foreign' => 'id'));

        $this->hasMany('AjusteDetalleRecurso as AjustesDetalleRecurso', array(
             'local' => 'id',
             'foreign' => 'ajuste_recurso_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}