<?php

/**
 * BaseTipoProfesor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $tipo
 * @property integer $numero_tipo
 * @property Doctrine_Collection $Concursos
 * @property Doctrine_Collection $RestriccionesConcurso
 * @property Doctrine_Collection $Personas
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getTipo()                  Returns the current record's "tipo" value
 * @method integer             getNumeroTipo()            Returns the current record's "numero_tipo" value
 * @method Doctrine_Collection getConcursos()             Returns the current record's "Concursos" collection
 * @method Doctrine_Collection getRestriccionesConcurso() Returns the current record's "RestriccionesConcurso" collection
 * @method Doctrine_Collection getPersonas()              Returns the current record's "Personas" collection
 * @method TipoProfesor        setId()                    Sets the current record's "id" value
 * @method TipoProfesor        setTipo()                  Sets the current record's "tipo" value
 * @method TipoProfesor        setNumeroTipo()            Sets the current record's "numero_tipo" value
 * @method TipoProfesor        setConcursos()             Sets the current record's "Concursos" collection
 * @method TipoProfesor        setRestriccionesConcurso() Sets the current record's "RestriccionesConcurso" collection
 * @method TipoProfesor        setPersonas()              Sets the current record's "Personas" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoProfesor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_profesor');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('tipo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('numero_tipo', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Concurso as Concursos', array(
             'refClass' => 'RestriccionConcurso',
             'local' => 'tipo_profesor_id',
             'foreign' => 'concurso_id'));

        $this->hasMany('RestriccionConcurso as RestriccionesConcurso', array(
             'local' => 'id',
             'foreign' => 'tipo_profesor_id'));

        $this->hasMany('Persona as Personas', array(
             'local' => 'id',
             'foreign' => 'tipo_profesor_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}