<?php

/**
 * BaseArchivoPostulacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_tipo_archivo
 * @property integer $id_persona_concurso
 * @property string $ruta
 * @property TipoArchivo $TipoArchivo
 * @property PersonaConcurso $PersonaConcurso
 * 
 * @method integer            getId()                  Returns the current record's "id" value
 * @method integer            getIdTipoArchivo()       Returns the current record's "id_tipo_archivo" value
 * @method integer            getIdPersonaConcurso()   Returns the current record's "id_persona_concurso" value
 * @method string             getRuta()                Returns the current record's "ruta" value
 * @method TipoArchivo        getTipoArchivo()         Returns the current record's "TipoArchivo" value
 * @method PersonaConcurso    getPersonaConcurso()     Returns the current record's "PersonaConcurso" value
 * @method ArchivoPostulacion setId()                  Sets the current record's "id" value
 * @method ArchivoPostulacion setIdTipoArchivo()       Sets the current record's "id_tipo_archivo" value
 * @method ArchivoPostulacion setIdPersonaConcurso()   Sets the current record's "id_persona_concurso" value
 * @method ArchivoPostulacion setRuta()                Sets the current record's "ruta" value
 * @method ArchivoPostulacion setTipoArchivo()         Sets the current record's "TipoArchivo" value
 * @method ArchivoPostulacion setPersonaConcurso()     Sets the current record's "PersonaConcurso" value
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchivoPostulacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archivo_postulacion');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('id_tipo_archivo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_persona_concurso', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ruta', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoArchivo', array(
             'local' => 'id_tipo_archivo',
             'foreign' => 'id'));

        $this->hasOne('PersonaConcurso', array(
             'local' => 'id_persona_concurso',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}