<?php

/**
 * BasePersonaConcurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $concurso_id
 * @property integer $tesista_id
 * @property timestamp $fecha_envio
 * @property integer $estado
 * @property string $titulo
 * @property string $categoria_arte
 * @property string $categoria_arte_otra
 * @property string $ruta_pdf_postulacion
 * @property integer $estado_evaluacion
 * @property boolean $esta_aprobado
 * @property string $codigo_proyecto
 * @property integer $codigo_numerico
 * @property Concurso $Concurso
 * @property Tesista $Tesista
 * @property Doctrine_Collection $ItemsConcurso
 * @property Doctrine_Collection $Personas
 * @property Doctrine_Collection $PersonasExternas
 * @property Doctrine_Collection $ParticipantesExternos
 * @property Doctrine_Collection $ParticipantesPostulacion
 * @property Doctrine_Collection $ConveniosDesempeno
 * @property Doctrine_Collection $Recursos
 * @property Doctrine_Collection $ArchivosPostulacion
 * @property Doctrine_Collection $Evaluaciones
 * 
 * @method integer             getId()                       Returns the current record's "id" value
 * @method integer             getConcursoId()               Returns the current record's "concurso_id" value
 * @method integer             getTesistaId()                Returns the current record's "tesista_id" value
 * @method timestamp           getFechaEnvio()               Returns the current record's "fecha_envio" value
 * @method integer             getEstado()                   Returns the current record's "estado" value
 * @method string              getTitulo()                   Returns the current record's "titulo" value
 * @method string              getCategoriaArte()            Returns the current record's "categoria_arte" value
 * @method string              getCategoriaArteOtra()        Returns the current record's "categoria_arte_otra" value
 * @method string              getRutaPdfPostulacion()       Returns the current record's "ruta_pdf_postulacion" value
 * @method integer             getEstadoEvaluacion()         Returns the current record's "estado_evaluacion" value
 * @method boolean             getEstaAprobado()             Returns the current record's "esta_aprobado" value
 * @method string              getCodigoProyecto()           Returns the current record's "codigo_proyecto" value
 * @method integer             getCodigoNumerico()           Returns the current record's "codigo_numerico" value
 * @method Concurso            getConcurso()                 Returns the current record's "Concurso" value
 * @method Tesista             getTesista()                  Returns the current record's "Tesista" value
 * @method Doctrine_Collection getItemsConcurso()            Returns the current record's "ItemsConcurso" collection
 * @method Doctrine_Collection getPersonas()                 Returns the current record's "Personas" collection
 * @method Doctrine_Collection getPersonasExternas()         Returns the current record's "PersonasExternas" collection
 * @method Doctrine_Collection getParticipantesExternos()    Returns the current record's "ParticipantesExternos" collection
 * @method Doctrine_Collection getParticipantesPostulacion() Returns the current record's "ParticipantesPostulacion" collection
 * @method Doctrine_Collection getConveniosDesempeno()       Returns the current record's "ConveniosDesempeno" collection
 * @method Doctrine_Collection getRecursos()                 Returns the current record's "Recursos" collection
 * @method Doctrine_Collection getArchivosPostulacion()      Returns the current record's "ArchivosPostulacion" collection
 * @method Doctrine_Collection getEvaluaciones()             Returns the current record's "Evaluaciones" collection
 * @method PersonaConcurso     setId()                       Sets the current record's "id" value
 * @method PersonaConcurso     setConcursoId()               Sets the current record's "concurso_id" value
 * @method PersonaConcurso     setTesistaId()                Sets the current record's "tesista_id" value
 * @method PersonaConcurso     setFechaEnvio()               Sets the current record's "fecha_envio" value
 * @method PersonaConcurso     setEstado()                   Sets the current record's "estado" value
 * @method PersonaConcurso     setTitulo()                   Sets the current record's "titulo" value
 * @method PersonaConcurso     setCategoriaArte()            Sets the current record's "categoria_arte" value
 * @method PersonaConcurso     setCategoriaArteOtra()        Sets the current record's "categoria_arte_otra" value
 * @method PersonaConcurso     setRutaPdfPostulacion()       Sets the current record's "ruta_pdf_postulacion" value
 * @method PersonaConcurso     setEstadoEvaluacion()         Sets the current record's "estado_evaluacion" value
 * @method PersonaConcurso     setEstaAprobado()             Sets the current record's "esta_aprobado" value
 * @method PersonaConcurso     setCodigoProyecto()           Sets the current record's "codigo_proyecto" value
 * @method PersonaConcurso     setCodigoNumerico()           Sets the current record's "codigo_numerico" value
 * @method PersonaConcurso     setConcurso()                 Sets the current record's "Concurso" value
 * @method PersonaConcurso     setTesista()                  Sets the current record's "Tesista" value
 * @method PersonaConcurso     setItemsConcurso()            Sets the current record's "ItemsConcurso" collection
 * @method PersonaConcurso     setPersonas()                 Sets the current record's "Personas" collection
 * @method PersonaConcurso     setPersonasExternas()         Sets the current record's "PersonasExternas" collection
 * @method PersonaConcurso     setParticipantesExternos()    Sets the current record's "ParticipantesExternos" collection
 * @method PersonaConcurso     setParticipantesPostulacion() Sets the current record's "ParticipantesPostulacion" collection
 * @method PersonaConcurso     setConveniosDesempeno()       Sets the current record's "ConveniosDesempeno" collection
 * @method PersonaConcurso     setRecursos()                 Sets the current record's "Recursos" collection
 * @method PersonaConcurso     setArchivosPostulacion()      Sets the current record's "ArchivosPostulacion" collection
 * @method PersonaConcurso     setEvaluaciones()             Sets the current record's "Evaluaciones" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersonaConcurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('persona_concurso');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('concurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tesista_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('fecha_envio', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('estado', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('categoria_arte', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('categoria_arte_otra', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('ruta_pdf_postulacion', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('estado_evaluacion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('esta_aprobado', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('codigo_proyecto', 'string', 40, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 40,
             ));
        $this->hasColumn('codigo_numerico', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Concurso', array(
             'local' => 'concurso_id',
             'foreign' => 'id'));

        $this->hasOne('Tesista', array(
             'local' => 'tesista_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ItemConcurso as ItemsConcurso', array(
             'refClass' => 'Recurso',
             'local' => 'persona_concurso_id',
             'foreign' => 'item_concurso_id'));

        $this->hasMany('Persona as Personas', array(
             'refClass' => 'ParticipantePostulacion',
             'local' => 'persona_concurso_id',
             'foreign' => 'persona_id'));

        $this->hasMany('PersonaExterna as PersonasExternas', array(
             'refClass' => 'ParticipanteExterno',
             'local' => 'persona_concurso_id',
             'foreign' => 'persona_externa_id'));

        $this->hasMany('ParticipanteExterno as ParticipantesExternos', array(
             'local' => 'id',
             'foreign' => 'persona_concurso_id'));

        $this->hasMany('ParticipantePostulacion as ParticipantesPostulacion', array(
             'local' => 'id',
             'foreign' => 'persona_concurso_id'));

        $this->hasMany('ConvenioDesempenoPostulacion as ConveniosDesempeno', array(
             'local' => 'id',
             'foreign' => 'persona_concurso_id'));

        $this->hasMany('Recurso as Recursos', array(
             'local' => 'id',
             'foreign' => 'persona_concurso_id'));

        $this->hasMany('ArchivoPostulacion as ArchivosPostulacion', array(
             'local' => 'id',
             'foreign' => 'id_persona_concurso'));

        $this->hasMany('Evaluacion as Evaluaciones', array(
             'local' => 'id',
             'foreign' => 'persona_concurso_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}