<?php

/**
 * BaseRespuestaAlternativa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $sesion_encuesta_id
 * @property integer $alternativa_id
 * @property SesionEncuesta $SesionEncuesta
 * @property Alternativa $Alternativa
 * 
 * @method integer              getId()                 Returns the current record's "id" value
 * @method integer              getSesionEncuestaId()   Returns the current record's "sesion_encuesta_id" value
 * @method integer              getAlternativaId()      Returns the current record's "alternativa_id" value
 * @method SesionEncuesta       getSesionEncuesta()     Returns the current record's "SesionEncuesta" value
 * @method Alternativa          getAlternativa()        Returns the current record's "Alternativa" value
 * @method RespuestaAlternativa setId()                 Sets the current record's "id" value
 * @method RespuestaAlternativa setSesionEncuestaId()   Sets the current record's "sesion_encuesta_id" value
 * @method RespuestaAlternativa setAlternativaId()      Sets the current record's "alternativa_id" value
 * @method RespuestaAlternativa setSesionEncuesta()     Sets the current record's "SesionEncuesta" value
 * @method RespuestaAlternativa setAlternativa()        Sets the current record's "Alternativa" value
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRespuestaAlternativa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('respuesta_alternativa');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('sesion_encuesta_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('alternativa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SesionEncuesta', array(
             'local' => 'sesion_encuesta_id',
             'foreign' => 'id'));

        $this->hasOne('Alternativa', array(
             'local' => 'alternativa_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}