<?php

/**
 * BaseRestriccionConcurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tipo_profesor_id
 * @property integer $concurso_id
 * @property TipoProfesor $TipoProfesor
 * @property Concurso $Concurso
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getTipoProfesorId()   Returns the current record's "tipo_profesor_id" value
 * @method integer             getConcursoId()       Returns the current record's "concurso_id" value
 * @method TipoProfesor        getTipoProfesor()     Returns the current record's "TipoProfesor" value
 * @method Concurso            getConcurso()         Returns the current record's "Concurso" value
 * @method RestriccionConcurso setId()               Sets the current record's "id" value
 * @method RestriccionConcurso setTipoProfesorId()   Sets the current record's "tipo_profesor_id" value
 * @method RestriccionConcurso setConcursoId()       Sets the current record's "concurso_id" value
 * @method RestriccionConcurso setTipoProfesor()     Sets the current record's "TipoProfesor" value
 * @method RestriccionConcurso setConcurso()         Sets the current record's "Concurso" value
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRestriccionConcurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('restriccion_concurso');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('tipo_profesor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('concurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoProfesor', array(
             'local' => 'tipo_profesor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Concurso', array(
             'local' => 'concurso_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}