<?php

/**
 * BaseArchivoRecurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $recurso_id
 * @property string $ruta
 * @property Recurso $Recurso
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getRecursoId()  Returns the current record's "recurso_id" value
 * @method string         getRuta()       Returns the current record's "ruta" value
 * @method Recurso        getRecurso()    Returns the current record's "Recurso" value
 * @method ArchivoRecurso setId()         Sets the current record's "id" value
 * @method ArchivoRecurso setRecursoId()  Sets the current record's "recurso_id" value
 * @method ArchivoRecurso setRuta()       Sets the current record's "ruta" value
 * @method ArchivoRecurso setRecurso()    Sets the current record's "Recurso" value
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchivoRecurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archivo_recurso');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('recurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ruta', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Recurso', array(
             'local' => 'recurso_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}