<?php

/**
 * BaseCompromisoDeConvenio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $convenio_desempeno_postulacion_id
 * @property integer $orden
 * @property string $texto_compromiso
 * @property ConvenioDesempenoPostulacion $ConvenioDesempenoPostulacion
 * 
 * @method integer                      getId()                                Returns the current record's "id" value
 * @method integer                      getConvenioDesempenoPostulacionId()    Returns the current record's "convenio_desempeno_postulacion_id" value
 * @method integer                      getOrden()                             Returns the current record's "orden" value
 * @method string                       getTextoCompromiso()                   Returns the current record's "texto_compromiso" value
 * @method ConvenioDesempenoPostulacion getConvenioDesempenoPostulacion()      Returns the current record's "ConvenioDesempenoPostulacion" value
 * @method CompromisoDeConvenio         setId()                                Sets the current record's "id" value
 * @method CompromisoDeConvenio         setConvenioDesempenoPostulacionId()    Sets the current record's "convenio_desempeno_postulacion_id" value
 * @method CompromisoDeConvenio         setOrden()                             Sets the current record's "orden" value
 * @method CompromisoDeConvenio         setTextoCompromiso()                   Sets the current record's "texto_compromiso" value
 * @method CompromisoDeConvenio         setConvenioDesempenoPostulacion()      Sets the current record's "ConvenioDesempenoPostulacion" value
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompromisoDeConvenio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('compromiso_de_convenio');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('convenio_desempeno_postulacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('orden', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('texto_compromiso', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ConvenioDesempenoPostulacion', array(
             'local' => 'convenio_desempeno_postulacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}