<?php

/**
 * BasePregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $encuesta_id
 * @property string $texto_pregunta
 * @property Encuesta $Encuesta
 * @property Doctrine_Collection $Alternativas
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getEncuestaId()     Returns the current record's "encuesta_id" value
 * @method string              getTextoPregunta()  Returns the current record's "texto_pregunta" value
 * @method Encuesta            getEncuesta()       Returns the current record's "Encuesta" value
 * @method Doctrine_Collection getAlternativas()   Returns the current record's "Alternativas" collection
 * @method Pregunta            setId()             Sets the current record's "id" value
 * @method Pregunta            setEncuestaId()     Sets the current record's "encuesta_id" value
 * @method Pregunta            setTextoPregunta()  Sets the current record's "texto_pregunta" value
 * @method Pregunta            setEncuesta()       Sets the current record's "Encuesta" value
 * @method Pregunta            setAlternativas()   Sets the current record's "Alternativas" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePregunta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pregunta');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('encuesta_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('texto_pregunta', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Encuesta', array(
             'local' => 'encuesta_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Alternativa as Alternativas', array(
             'local' => 'id',
             'foreign' => 'pregunta_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}