<?php

/**
 * BasePersonaExterna
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $rut
 * @property string $dv
 * @property string $nombre
 * @property string $apellido1
 * @property string $apellido2
 * @property string $nombre_universidad
 * @property string $telefono
 * @property string $email
 * @property string $jerarquia
 * @property string $compromiso_contractual_con_la_universidad
 * @property Doctrine_Collection $ParticipanteExterno
 * @property Doctrine_Collection $PersonaConcursos
 * 
 * @method integer             getId()                                        Returns the current record's "id" value
 * @method integer             getRut()                                       Returns the current record's "rut" value
 * @method string              getDv()                                        Returns the current record's "dv" value
 * @method string              getNombre()                                    Returns the current record's "nombre" value
 * @method string              getApellido1()                                 Returns the current record's "apellido1" value
 * @method string              getApellido2()                                 Returns the current record's "apellido2" value
 * @method string              getNombreUniversidad()                         Returns the current record's "nombre_universidad" value
 * @method string              getTelefono()                                  Returns the current record's "telefono" value
 * @method string              getEmail()                                     Returns the current record's "email" value
 * @method string              getJerarquia()                                 Returns the current record's "jerarquia" value
 * @method string              getCompromisoContractualConLaUniversidad()     Returns the current record's "compromiso_contractual_con_la_universidad" value
 * @method Doctrine_Collection getParticipanteExterno()                       Returns the current record's "ParticipanteExterno" collection
 * @method Doctrine_Collection getPersonaConcursos()                          Returns the current record's "PersonaConcursos" collection
 * @method PersonaExterna      setId()                                        Sets the current record's "id" value
 * @method PersonaExterna      setRut()                                       Sets the current record's "rut" value
 * @method PersonaExterna      setDv()                                        Sets the current record's "dv" value
 * @method PersonaExterna      setNombre()                                    Sets the current record's "nombre" value
 * @method PersonaExterna      setApellido1()                                 Sets the current record's "apellido1" value
 * @method PersonaExterna      setApellido2()                                 Sets the current record's "apellido2" value
 * @method PersonaExterna      setNombreUniversidad()                         Sets the current record's "nombre_universidad" value
 * @method PersonaExterna      setTelefono()                                  Sets the current record's "telefono" value
 * @method PersonaExterna      setEmail()                                     Sets the current record's "email" value
 * @method PersonaExterna      setJerarquia()                                 Sets the current record's "jerarquia" value
 * @method PersonaExterna      setCompromisoContractualConLaUniversidad()     Sets the current record's "compromiso_contractual_con_la_universidad" value
 * @method PersonaExterna      setParticipanteExterno()                       Sets the current record's "ParticipanteExterno" collection
 * @method PersonaExterna      setPersonaConcursos()                          Sets the current record's "PersonaConcursos" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersonaExterna extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('persona_externa');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('rut', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('dv', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('apellido1', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('apellido2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nombre_universidad', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('telefono', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('jerarquia', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('compromiso_contractual_con_la_universidad', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ParticipanteExterno', array(
             'local' => 'id',
             'foreign' => 'persona_externa_id'));

        $this->hasMany('PersonaConcurso as PersonaConcursos', array(
             'refClass' => 'ParticipanteExterno',
             'local' => 'persona_externa_id',
             'foreign' => 'persona_concurso_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}