<?php

/**
 * BaseCompromisoDeConcurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $concurso_id
 * @property integer $tipo
 * @property integer $orden
 * @property string $texto
 * @property Concurso $Concurso
 * 
 * @method integer              getId()          Returns the current record's "id" value
 * @method integer              getConcursoId()  Returns the current record's "concurso_id" value
 * @method integer              getTipo()        Returns the current record's "tipo" value
 * @method integer              getOrden()       Returns the current record's "orden" value
 * @method string               getTexto()       Returns the current record's "texto" value
 * @method Concurso             getConcurso()    Returns the current record's "Concurso" value
 * @method CompromisoDeConcurso setId()          Sets the current record's "id" value
 * @method CompromisoDeConcurso setConcursoId()  Sets the current record's "concurso_id" value
 * @method CompromisoDeConcurso setTipo()        Sets the current record's "tipo" value
 * @method CompromisoDeConcurso setOrden()       Sets the current record's "orden" value
 * @method CompromisoDeConcurso setTexto()       Sets the current record's "texto" value
 * @method CompromisoDeConcurso setConcurso()    Sets the current record's "Concurso" value
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompromisoDeConcurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('compromiso_de_concurso');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('concurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 1,
             ));
        $this->hasColumn('orden', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('texto', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Concurso', array(
             'local' => 'concurso_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}