<?php

/**
 * BaseConcurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $convocatoria_id
 * @property string $nombre_concurso
 * @property string $acronimo
 * @property integer $monto_maximo
 * @property timestamp $inicio_postulacion
 * @property timestamp $termino_postulacion
 * @property integer $duracion
 * @property integer $porcentaje_formulacion
 * @property integer $porcentaje_productividad
 * @property integer $maximo_isis
 * @property integer $maximo_proyectos_fondecyt
 * @property integer $maximo_proyectos_internos
 * @property Convocatoria $Convocatoria
 * @property Doctrine_Collection $Items
 * @property Doctrine_Collection $TiposProfesores
 * @property Doctrine_Collection $TipoArchivos
 * @property Doctrine_Collection $RestriccionesConcurso
 * @property Doctrine_Collection $Compromisos
 * @property Doctrine_Collection $PorcentajesProductividad
 * @property Doctrine_Collection $ItemConcurso
 * @property Doctrine_Collection $Postulaciones
 * @property Doctrine_Collection $ConcursoTipoArchivos
 * 
 * @method integer             getId()                        Returns the current record's "id" value
 * @method integer             getConvocatoriaId()            Returns the current record's "convocatoria_id" value
 * @method string              getNombreConcurso()            Returns the current record's "nombre_concurso" value
 * @method string              getAcronimo()                  Returns the current record's "acronimo" value
 * @method integer             getMontoMaximo()               Returns the current record's "monto_maximo" value
 * @method timestamp           getInicioPostulacion()         Returns the current record's "inicio_postulacion" value
 * @method timestamp           getTerminoPostulacion()        Returns the current record's "termino_postulacion" value
 * @method integer             getDuracion()                  Returns the current record's "duracion" value
 * @method integer             getPorcentajeFormulacion()     Returns the current record's "porcentaje_formulacion" value
 * @method integer             getPorcentajeProductividad()   Returns the current record's "porcentaje_productividad" value
 * @method integer             getMaximoIsis()                Returns the current record's "maximo_isis" value
 * @method integer             getMaximoProyectosFondecyt()   Returns the current record's "maximo_proyectos_fondecyt" value
 * @method integer             getMaximoProyectosInternos()   Returns the current record's "maximo_proyectos_internos" value
 * @method Convocatoria        getConvocatoria()              Returns the current record's "Convocatoria" value
 * @method Doctrine_Collection getItems()                     Returns the current record's "Items" collection
 * @method Doctrine_Collection getTiposProfesores()           Returns the current record's "TiposProfesores" collection
 * @method Doctrine_Collection getTipoArchivos()              Returns the current record's "TipoArchivos" collection
 * @method Doctrine_Collection getRestriccionesConcurso()     Returns the current record's "RestriccionesConcurso" collection
 * @method Doctrine_Collection getCompromisos()               Returns the current record's "Compromisos" collection
 * @method Doctrine_Collection getPorcentajesProductividad()  Returns the current record's "PorcentajesProductividad" collection
 * @method Doctrine_Collection getItemConcurso()              Returns the current record's "ItemConcurso" collection
 * @method Doctrine_Collection getPostulaciones()             Returns the current record's "Postulaciones" collection
 * @method Doctrine_Collection getConcursoTipoArchivos()      Returns the current record's "ConcursoTipoArchivos" collection
 * @method Concurso            setId()                        Sets the current record's "id" value
 * @method Concurso            setConvocatoriaId()            Sets the current record's "convocatoria_id" value
 * @method Concurso            setNombreConcurso()            Sets the current record's "nombre_concurso" value
 * @method Concurso            setAcronimo()                  Sets the current record's "acronimo" value
 * @method Concurso            setMontoMaximo()               Sets the current record's "monto_maximo" value
 * @method Concurso            setInicioPostulacion()         Sets the current record's "inicio_postulacion" value
 * @method Concurso            setTerminoPostulacion()        Sets the current record's "termino_postulacion" value
 * @method Concurso            setDuracion()                  Sets the current record's "duracion" value
 * @method Concurso            setPorcentajeFormulacion()     Sets the current record's "porcentaje_formulacion" value
 * @method Concurso            setPorcentajeProductividad()   Sets the current record's "porcentaje_productividad" value
 * @method Concurso            setMaximoIsis()                Sets the current record's "maximo_isis" value
 * @method Concurso            setMaximoProyectosFondecyt()   Sets the current record's "maximo_proyectos_fondecyt" value
 * @method Concurso            setMaximoProyectosInternos()   Sets the current record's "maximo_proyectos_internos" value
 * @method Concurso            setConvocatoria()              Sets the current record's "Convocatoria" value
 * @method Concurso            setItems()                     Sets the current record's "Items" collection
 * @method Concurso            setTiposProfesores()           Sets the current record's "TiposProfesores" collection
 * @method Concurso            setTipoArchivos()              Sets the current record's "TipoArchivos" collection
 * @method Concurso            setRestriccionesConcurso()     Sets the current record's "RestriccionesConcurso" collection
 * @method Concurso            setCompromisos()               Sets the current record's "Compromisos" collection
 * @method Concurso            setPorcentajesProductividad()  Sets the current record's "PorcentajesProductividad" collection
 * @method Concurso            setItemConcurso()              Sets the current record's "ItemConcurso" collection
 * @method Concurso            setPostulaciones()             Sets the current record's "Postulaciones" collection
 * @method Concurso            setConcursoTipoArchivos()      Sets the current record's "ConcursoTipoArchivos" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConcurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('concurso');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('convocatoria_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('nombre_concurso', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('acronimo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('monto_maximo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('inicio_postulacion', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('termino_postulacion', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('duracion', 'integer', null, array(
             'type' => 'integer',
             'default' => 9,
             ));
        $this->hasColumn('porcentaje_formulacion', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('porcentaje_productividad', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('maximo_isis', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('maximo_proyectos_fondecyt', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('maximo_proyectos_internos', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Convocatoria', array(
             'local' => 'convocatoria_id',
             'foreign' => 'id'));

        $this->hasMany('Item as Items', array(
             'refClass' => 'ItemConcurso',
             'local' => 'concurso_id',
             'foreign' => 'item_id'));

        $this->hasMany('TipoProfesor as TiposProfesores', array(
             'refClass' => 'RestriccionConcurso',
             'local' => 'concurso_id',
             'foreign' => 'tipo_profesor_id'));

        $this->hasMany('TipoArchivo as TipoArchivos', array(
             'refClass' => 'ConcursoTipoArchivo',
             'local' => 'concurso_id',
             'foreign' => 'tipo_archivo_id'));

        $this->hasMany('RestriccionConcurso as RestriccionesConcurso', array(
             'local' => 'id',
             'foreign' => 'concurso_id'));

        $this->hasMany('CompromisoDeConcurso as Compromisos', array(
             'local' => 'id',
             'foreign' => 'concurso_id'));

        $this->hasMany('PorcentajeProductividadConcurso as PorcentajesProductividad', array(
             'local' => 'id',
             'foreign' => 'concurso_id'));

        $this->hasMany('ItemConcurso', array(
             'local' => 'id',
             'foreign' => 'concurso_id'));

        $this->hasMany('PersonaConcurso as Postulaciones', array(
             'local' => 'id',
             'foreign' => 'concurso_id'));

        $this->hasMany('ConcursoTipoArchivo as ConcursoTipoArchivos', array(
             'local' => 'id',
             'foreign' => 'concurso_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}