<?php

/**
 * BasePorcentajeProductividadConcurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $concurso_id
 * @property string $tipo_productividad
 * @property integer $porcentaje
 * @property Concurso $Concurso
 * @property Doctrine_Collection $NotasProductividad
 * 
 * @method integer                         getId()                 Returns the current record's "id" value
 * @method integer                         getConcursoId()         Returns the current record's "concurso_id" value
 * @method string                          getTipoProductividad()  Returns the current record's "tipo_productividad" value
 * @method integer                         getPorcentaje()         Returns the current record's "porcentaje" value
 * @method Concurso                        getConcurso()           Returns the current record's "Concurso" value
 * @method Doctrine_Collection             getNotasProductividad() Returns the current record's "NotasProductividad" collection
 * @method PorcentajeProductividadConcurso setId()                 Sets the current record's "id" value
 * @method PorcentajeProductividadConcurso setConcursoId()         Sets the current record's "concurso_id" value
 * @method PorcentajeProductividadConcurso setTipoProductividad()  Sets the current record's "tipo_productividad" value
 * @method PorcentajeProductividadConcurso setPorcentaje()         Sets the current record's "porcentaje" value
 * @method PorcentajeProductividadConcurso setConcurso()           Sets the current record's "Concurso" value
 * @method PorcentajeProductividadConcurso setNotasProductividad() Sets the current record's "NotasProductividad" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePorcentajeProductividadConcurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('porcentaje_productividad_concurso');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('concurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo_productividad', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('porcentaje', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Concurso', array(
             'local' => 'concurso_id',
             'foreign' => 'id'));

        $this->hasMany('NotaProductividad as NotasProductividad', array(
             'local' => 'id',
             'foreign' => 'porcentaje_productividad_concurso_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}