<?php

/**
 * BaseTesista
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $doctorado_acreditado_id
 * @property integer $rut
 * @property string $dv
 * @property string $nombre
 * @property string $apellido1
 * @property string $apellido2
 * @property string $sexo
 * @property string $telefono
 * @property string $email
 * @property string $ruta_notas
 * @property DoctoradoAcreditado $DoctoradoAcreditado
 * @property Doctrine_Collection $PersonaConcurso
 * 
 * @method integer             getId()                      Returns the current record's "id" value
 * @method integer             getDoctoradoAcreditadoId()   Returns the current record's "doctorado_acreditado_id" value
 * @method integer             getRut()                     Returns the current record's "rut" value
 * @method string              getDv()                      Returns the current record's "dv" value
 * @method string              getNombre()                  Returns the current record's "nombre" value
 * @method string              getApellido1()               Returns the current record's "apellido1" value
 * @method string              getApellido2()               Returns the current record's "apellido2" value
 * @method string              getSexo()                    Returns the current record's "sexo" value
 * @method string              getTelefono()                Returns the current record's "telefono" value
 * @method string              getEmail()                   Returns the current record's "email" value
 * @method string              getRutaNotas()               Returns the current record's "ruta_notas" value
 * @method DoctoradoAcreditado getDoctoradoAcreditado()     Returns the current record's "DoctoradoAcreditado" value
 * @method Doctrine_Collection getPersonaConcurso()         Returns the current record's "PersonaConcurso" collection
 * @method Tesista             setId()                      Sets the current record's "id" value
 * @method Tesista             setDoctoradoAcreditadoId()   Sets the current record's "doctorado_acreditado_id" value
 * @method Tesista             setRut()                     Sets the current record's "rut" value
 * @method Tesista             setDv()                      Sets the current record's "dv" value
 * @method Tesista             setNombre()                  Sets the current record's "nombre" value
 * @method Tesista             setApellido1()               Sets the current record's "apellido1" value
 * @method Tesista             setApellido2()               Sets the current record's "apellido2" value
 * @method Tesista             setSexo()                    Sets the current record's "sexo" value
 * @method Tesista             setTelefono()                Sets the current record's "telefono" value
 * @method Tesista             setEmail()                   Sets the current record's "email" value
 * @method Tesista             setRutaNotas()               Sets the current record's "ruta_notas" value
 * @method Tesista             setDoctoradoAcreditado()     Sets the current record's "DoctoradoAcreditado" value
 * @method Tesista             setPersonaConcurso()         Sets the current record's "PersonaConcurso" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTesista extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tesista');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('doctorado_acreditado_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('rut', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('dv', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('apellido1', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('apellido2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sexo', 'string', 1, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 1,
             ));
        $this->hasColumn('telefono', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ruta_notas', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DoctoradoAcreditado', array(
             'local' => 'doctorado_acreditado_id',
             'foreign' => 'id'));

        $this->hasMany('PersonaConcurso', array(
             'local' => 'id',
             'foreign' => 'tesista_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}