<?php

/**
 * BaseNotaFormulacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $evaluacion_id
 * @property integer $porcentaje_evaluacion_id
 * @property integer $nota
 * @property Evaluacion $Evaluacion
 * @property PorcentajeEvaluacion $PorcentajeEvaluacion
 * 
 * @method integer              getId()                       Returns the current record's "id" value
 * @method integer              getEvaluacionId()             Returns the current record's "evaluacion_id" value
 * @method integer              getPorcentajeEvaluacionId()   Returns the current record's "porcentaje_evaluacion_id" value
 * @method integer              getNota()                     Returns the current record's "nota" value
 * @method Evaluacion           getEvaluacion()               Returns the current record's "Evaluacion" value
 * @method PorcentajeEvaluacion getPorcentajeEvaluacion()     Returns the current record's "PorcentajeEvaluacion" value
 * @method NotaFormulacion      setId()                       Sets the current record's "id" value
 * @method NotaFormulacion      setEvaluacionId()             Sets the current record's "evaluacion_id" value
 * @method NotaFormulacion      setPorcentajeEvaluacionId()   Sets the current record's "porcentaje_evaluacion_id" value
 * @method NotaFormulacion      setNota()                     Sets the current record's "nota" value
 * @method NotaFormulacion      setEvaluacion()               Sets the current record's "Evaluacion" value
 * @method NotaFormulacion      setPorcentajeEvaluacion()     Sets the current record's "PorcentajeEvaluacion" value
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotaFormulacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nota_formulacion');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('evaluacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('porcentaje_evaluacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nota', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Evaluacion', array(
             'local' => 'evaluacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('PorcentajeEvaluacion', array(
             'local' => 'porcentaje_evaluacion_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}