<?php

/**
 * BaseFacultad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $orden
 * @property string $nombre
 * @property Doctrine_Collection $UnidadesAcademicas
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getOrden()              Returns the current record's "orden" value
 * @method string              getNombre()             Returns the current record's "nombre" value
 * @method Doctrine_Collection getUnidadesAcademicas() Returns the current record's "UnidadesAcademicas" collection
 * @method Facultad            setId()                 Sets the current record's "id" value
 * @method Facultad            setOrden()              Sets the current record's "orden" value
 * @method Facultad            setNombre()             Sets the current record's "nombre" value
 * @method Facultad            setUnidadesAcademicas() Sets the current record's "UnidadesAcademicas" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFacultad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('facultad');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('orden', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UnidadAcademica as UnidadesAcademicas', array(
             'local' => 'id',
             'foreign' => 'facultad_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}