<?php

/**
 * BaseEvaluacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $persona_sistema_id
 * @property integer $persona_concurso_id
 * @property integer $nota
 * @property integer $estado
 * @property string $comentario
 * @property boolean $recomiendo_adjudicacion
 * @property PersonaSistema $PersonaSistema
 * @property PersonaConcurso $PersonaConcurso
 * @property Doctrine_Collection $NotasFormulacion
 * @property Doctrine_Collection $AjustesRecurso
 * @property Doctrine_Collection $NotasProductividad
 * 
 * @method integer             getId()                      Returns the current record's "id" value
 * @method integer             getPersonaSistemaId()        Returns the current record's "persona_sistema_id" value
 * @method integer             getPersonaConcursoId()       Returns the current record's "persona_concurso_id" value
 * @method integer             getNota()                    Returns the current record's "nota" value
 * @method integer             getEstado()                  Returns the current record's "estado" value
 * @method string              getComentario()              Returns the current record's "comentario" value
 * @method boolean             getRecomiendoAdjudicacion()  Returns the current record's "recomiendo_adjudicacion" value
 * @method PersonaSistema      getPersonaSistema()          Returns the current record's "PersonaSistema" value
 * @method PersonaConcurso     getPersonaConcurso()         Returns the current record's "PersonaConcurso" value
 * @method Doctrine_Collection getNotasFormulacion()        Returns the current record's "NotasFormulacion" collection
 * @method Doctrine_Collection getAjustesRecurso()          Returns the current record's "AjustesRecurso" collection
 * @method Doctrine_Collection getNotasProductividad()      Returns the current record's "NotasProductividad" collection
 * @method Evaluacion          setId()                      Sets the current record's "id" value
 * @method Evaluacion          setPersonaSistemaId()        Sets the current record's "persona_sistema_id" value
 * @method Evaluacion          setPersonaConcursoId()       Sets the current record's "persona_concurso_id" value
 * @method Evaluacion          setNota()                    Sets the current record's "nota" value
 * @method Evaluacion          setEstado()                  Sets the current record's "estado" value
 * @method Evaluacion          setComentario()              Sets the current record's "comentario" value
 * @method Evaluacion          setRecomiendoAdjudicacion()  Sets the current record's "recomiendo_adjudicacion" value
 * @method Evaluacion          setPersonaSistema()          Sets the current record's "PersonaSistema" value
 * @method Evaluacion          setPersonaConcurso()         Sets the current record's "PersonaConcurso" value
 * @method Evaluacion          setNotasFormulacion()        Sets the current record's "NotasFormulacion" collection
 * @method Evaluacion          setAjustesRecurso()          Sets the current record's "AjustesRecurso" collection
 * @method Evaluacion          setNotasProductividad()      Sets the current record's "NotasProductividad" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvaluacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evaluacion');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('persona_sistema_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('persona_concurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nota', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('estado', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('comentario', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('recomiendo_adjudicacion', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PersonaSistema', array(
             'local' => 'persona_sistema_id',
             'foreign' => 'id'));

        $this->hasOne('PersonaConcurso', array(
             'local' => 'persona_concurso_id',
             'foreign' => 'id'));

        $this->hasMany('NotaFormulacion as NotasFormulacion', array(
             'local' => 'id',
             'foreign' => 'evaluacion_id'));

        $this->hasMany('AjusteRecurso as AjustesRecurso', array(
             'local' => 'id',
             'foreign' => 'evaluacion_id'));

        $this->hasMany('NotaProductividad as NotasProductividad', array(
             'local' => 'id',
             'foreign' => 'evaluacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}