<?php

/**
 * BaseDetalleRecursoGastosOperacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $detalle_recurso_id
 * @property integer $tipo_de_gasto
 * @property integer $monto
 * @property DetalleRecurso $DetalleRecurso
 * @property Doctrine_Collection $AjustesDetalleRecursoGastosOperacion
 * 
 * @method integer                       getId()                                   Returns the current record's "id" value
 * @method integer                       getDetalleRecursoId()                     Returns the current record's "detalle_recurso_id" value
 * @method integer                       getTipoDeGasto()                          Returns the current record's "tipo_de_gasto" value
 * @method integer                       getMonto()                                Returns the current record's "monto" value
 * @method DetalleRecurso                getDetalleRecurso()                       Returns the current record's "DetalleRecurso" value
 * @method Doctrine_Collection           getAjustesDetalleRecursoGastosOperacion() Returns the current record's "AjustesDetalleRecursoGastosOperacion" collection
 * @method DetalleRecursoGastosOperacion setId()                                   Sets the current record's "id" value
 * @method DetalleRecursoGastosOperacion setDetalleRecursoId()                     Sets the current record's "detalle_recurso_id" value
 * @method DetalleRecursoGastosOperacion setTipoDeGasto()                          Sets the current record's "tipo_de_gasto" value
 * @method DetalleRecursoGastosOperacion setMonto()                                Sets the current record's "monto" value
 * @method DetalleRecursoGastosOperacion setDetalleRecurso()                       Sets the current record's "DetalleRecurso" value
 * @method DetalleRecursoGastosOperacion setAjustesDetalleRecursoGastosOperacion() Sets the current record's "AjustesDetalleRecursoGastosOperacion" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetalleRecursoGastosOperacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalle_recurso_gastos_operacion');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('detalle_recurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo_de_gasto', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('monto', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DetalleRecurso', array(
             'local' => 'detalle_recurso_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('AjusteDetalleRecursoGastosOperacion as AjustesDetalleRecursoGastosOperacion', array(
             'local' => 'id',
             'foreign' => 'detalle_recurso_gastos_operacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}