<?php

/**
 * BaseLibroDePersona
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $persona_id
 * @property string $nombre
 * @property string $editorial
 * @property integer $anio
 * @property Persona $Persona
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getPersonaId()  Returns the current record's "persona_id" value
 * @method string         getNombre()     Returns the current record's "nombre" value
 * @method string         getEditorial()  Returns the current record's "editorial" value
 * @method integer        getAnio()       Returns the current record's "anio" value
 * @method Persona        getPersona()    Returns the current record's "Persona" value
 * @method LibroDePersona setId()         Sets the current record's "id" value
 * @method LibroDePersona setPersonaId()  Sets the current record's "persona_id" value
 * @method LibroDePersona setNombre()     Sets the current record's "nombre" value
 * @method LibroDePersona setEditorial()  Sets the current record's "editorial" value
 * @method LibroDePersona setAnio()       Sets the current record's "anio" value
 * @method LibroDePersona setPersona()    Sets the current record's "Persona" value
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLibroDePersona extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('libro_de_persona');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('persona_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('editorial', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('anio', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Persona', array(
             'local' => 'persona_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}