<?php

/**
 * BaseConcursoTipoArchivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $concurso_id
 * @property integer $tipo_archivo_id
 * @property Concurso $Concurso
 * @property TipoArchivo $TipoArchivo
 * @property Doctrine_Collection $PorcentajesEvaluacion
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getConcursoId()            Returns the current record's "concurso_id" value
 * @method integer             getTipoArchivoId()         Returns the current record's "tipo_archivo_id" value
 * @method Concurso            getConcurso()              Returns the current record's "Concurso" value
 * @method TipoArchivo         getTipoArchivo()           Returns the current record's "TipoArchivo" value
 * @method Doctrine_Collection getPorcentajesEvaluacion() Returns the current record's "PorcentajesEvaluacion" collection
 * @method ConcursoTipoArchivo setId()                    Sets the current record's "id" value
 * @method ConcursoTipoArchivo setConcursoId()            Sets the current record's "concurso_id" value
 * @method ConcursoTipoArchivo setTipoArchivoId()         Sets the current record's "tipo_archivo_id" value
 * @method ConcursoTipoArchivo setConcurso()              Sets the current record's "Concurso" value
 * @method ConcursoTipoArchivo setTipoArchivo()           Sets the current record's "TipoArchivo" value
 * @method ConcursoTipoArchivo setPorcentajesEvaluacion() Sets the current record's "PorcentajesEvaluacion" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConcursoTipoArchivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('concurso_tipo_archivo');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('concurso_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tipo_archivo_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Concurso', array(
             'local' => 'concurso_id',
             'foreign' => 'id'));

        $this->hasOne('TipoArchivo', array(
             'local' => 'tipo_archivo_id',
             'foreign' => 'id'));

        $this->hasMany('PorcentajeEvaluacion as PorcentajesEvaluacion', array(
             'local' => 'id',
             'foreign' => 'concurso_tipo_archivo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}