<?php

/**
 * BaseAjusteDetalleRecurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $ajuste_recurso_id
 * @property integer $detalle_recurso_id
 * @property integer $monto_aprobado
 * @property AjusteRecurso $AjusteRecurso
 * @property DetalleRecurso $DetalleRecurso
 * @property Doctrine_Collection $AjustesDetalleRecursoGastosOperacion
 * 
 * @method integer              getId()                                   Returns the current record's "id" value
 * @method integer              getAjusteRecursoId()                      Returns the current record's "ajuste_recurso_id" value
 * @method integer              getDetalleRecursoId()                     Returns the current record's "detalle_recurso_id" value
 * @method integer              getMontoAprobado()                        Returns the current record's "monto_aprobado" value
 * @method AjusteRecurso        getAjusteRecurso()                        Returns the current record's "AjusteRecurso" value
 * @method DetalleRecurso       getDetalleRecurso()                       Returns the current record's "DetalleRecurso" value
 * @method Doctrine_Collection  getAjustesDetalleRecursoGastosOperacion() Returns the current record's "AjustesDetalleRecursoGastosOperacion" collection
 * @method AjusteDetalleRecurso setId()                                   Sets the current record's "id" value
 * @method AjusteDetalleRecurso setAjusteRecursoId()                      Sets the current record's "ajuste_recurso_id" value
 * @method AjusteDetalleRecurso setDetalleRecursoId()                     Sets the current record's "detalle_recurso_id" value
 * @method AjusteDetalleRecurso setMontoAprobado()                        Sets the current record's "monto_aprobado" value
 * @method AjusteDetalleRecurso setAjusteRecurso()                        Sets the current record's "AjusteRecurso" value
 * @method AjusteDetalleRecurso setDetalleRecurso()                       Sets the current record's "DetalleRecurso" value
 * @method AjusteDetalleRecurso setAjustesDetalleRecursoGastosOperacion() Sets the current record's "AjustesDetalleRecursoGastosOperacion" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAjusteDetalleRecurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ajuste_detalle_recurso');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('ajuste_recurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('detalle_recurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('monto_aprobado', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AjusteRecurso', array(
             'local' => 'ajuste_recurso_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('DetalleRecurso', array(
             'local' => 'detalle_recurso_id',
             'foreign' => 'id'));

        $this->hasMany('AjusteDetalleRecursoGastosOperacion as AjustesDetalleRecursoGastosOperacion', array(
             'local' => 'id',
             'foreign' => 'ajuste_detalle_recurso_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}