<?php

/**
 * BaseSesionEncuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $persona_id
 * @property integer $encuesta_id
 * @property timestamp $fecha_inicio_sesion
 * @property Persona $Persona
 * @property Encuesta $Encuesta
 * @property Doctrine_Collection $Respuestas
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method integer             getPersonaId()           Returns the current record's "persona_id" value
 * @method integer             getEncuestaId()          Returns the current record's "encuesta_id" value
 * @method timestamp           getFechaInicioSesion()   Returns the current record's "fecha_inicio_sesion" value
 * @method Persona             getPersona()             Returns the current record's "Persona" value
 * @method Encuesta            getEncuesta()            Returns the current record's "Encuesta" value
 * @method Doctrine_Collection getRespuestas()          Returns the current record's "Respuestas" collection
 * @method SesionEncuesta      setId()                  Sets the current record's "id" value
 * @method SesionEncuesta      setPersonaId()           Sets the current record's "persona_id" value
 * @method SesionEncuesta      setEncuestaId()          Sets the current record's "encuesta_id" value
 * @method SesionEncuesta      setFechaInicioSesion()   Sets the current record's "fecha_inicio_sesion" value
 * @method SesionEncuesta      setPersona()             Sets the current record's "Persona" value
 * @method SesionEncuesta      setEncuesta()            Sets the current record's "Encuesta" value
 * @method SesionEncuesta      setRespuestas()          Sets the current record's "Respuestas" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSesionEncuesta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sesion_encuesta');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('persona_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('encuesta_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fecha_inicio_sesion', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Persona', array(
             'local' => 'persona_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Encuesta', array(
             'local' => 'encuesta_id',
             'foreign' => 'id'));

        $this->hasMany('RespuestaAlternativa as Respuestas', array(
             'local' => 'id',
             'foreign' => 'sesion_encuesta_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}