<?php

/**
 * BaseConvocatoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $anio
 * @property string $nombre
 * @property boolean $esta_vigente
 * @property timestamp $fecha_firma_convenio
 * @property timestamp $fecha_termino_convenio
 * @property Doctrine_Collection $Concursos
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method integer             getAnio()                   Returns the current record's "anio" value
 * @method string              getNombre()                 Returns the current record's "nombre" value
 * @method boolean             getEstaVigente()            Returns the current record's "esta_vigente" value
 * @method timestamp           getFechaFirmaConvenio()     Returns the current record's "fecha_firma_convenio" value
 * @method timestamp           getFechaTerminoConvenio()   Returns the current record's "fecha_termino_convenio" value
 * @method Doctrine_Collection getConcursos()              Returns the current record's "Concursos" collection
 * @method Convocatoria        setId()                     Sets the current record's "id" value
 * @method Convocatoria        setAnio()                   Sets the current record's "anio" value
 * @method Convocatoria        setNombre()                 Sets the current record's "nombre" value
 * @method Convocatoria        setEstaVigente()            Sets the current record's "esta_vigente" value
 * @method Convocatoria        setFechaFirmaConvenio()     Sets the current record's "fecha_firma_convenio" value
 * @method Convocatoria        setFechaTerminoConvenio()   Sets the current record's "fecha_termino_convenio" value
 * @method Convocatoria        setConcursos()              Sets the current record's "Concursos" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConvocatoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('convocatoria');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('anio', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('esta_vigente', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('fecha_firma_convenio', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('fecha_termino_convenio', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Concurso as Concursos', array(
             'local' => 'id',
             'foreign' => 'convocatoria_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}