<?php

/**
 * BaseNotaProductividad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $evaluacion_id
 * @property integer $porcentaje_productividad_concurso_id
 * @property integer $nota
 * @property PorcentajeProductividadConcurso $PorcentajeProductividadConcurso
 * @property Evaluacion $Evaluacion
 * 
 * @method integer                         getId()                                   Returns the current record's "id" value
 * @method integer                         getEvaluacionId()                         Returns the current record's "evaluacion_id" value
 * @method integer                         getPorcentajeProductividadConcursoId()    Returns the current record's "porcentaje_productividad_concurso_id" value
 * @method integer                         getNota()                                 Returns the current record's "nota" value
 * @method PorcentajeProductividadConcurso getPorcentajeProductividadConcurso()      Returns the current record's "PorcentajeProductividadConcurso" value
 * @method Evaluacion                      getEvaluacion()                           Returns the current record's "Evaluacion" value
 * @method NotaProductividad               setId()                                   Sets the current record's "id" value
 * @method NotaProductividad               setEvaluacionId()                         Sets the current record's "evaluacion_id" value
 * @method NotaProductividad               setPorcentajeProductividadConcursoId()    Sets the current record's "porcentaje_productividad_concurso_id" value
 * @method NotaProductividad               setNota()                                 Sets the current record's "nota" value
 * @method NotaProductividad               setPorcentajeProductividadConcurso()      Sets the current record's "PorcentajeProductividadConcurso" value
 * @method NotaProductividad               setEvaluacion()                           Sets the current record's "Evaluacion" value
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotaProductividad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nota_productividad');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('evaluacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('porcentaje_productividad_concurso_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('nota', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PorcentajeProductividadConcurso', array(
             'local' => 'porcentaje_productividad_concurso_id',
             'foreign' => 'id'));

        $this->hasOne('Evaluacion', array(
             'local' => 'evaluacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}