<?php

/**
 * BaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre_item
 * @property string $acronimo
 * @property boolean $tiene_subitem
 * @property Doctrine_Collection $Concursos
 * @property Doctrine_Collection $Subitems
 * @property Doctrine_Collection $ItemConcurso
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getNombreItem()    Returns the current record's "nombre_item" value
 * @method string              getAcronimo()      Returns the current record's "acronimo" value
 * @method boolean             getTieneSubitem()  Returns the current record's "tiene_subitem" value
 * @method Doctrine_Collection getConcursos()     Returns the current record's "Concursos" collection
 * @method Doctrine_Collection getSubitems()      Returns the current record's "Subitems" collection
 * @method Doctrine_Collection getItemConcurso()  Returns the current record's "ItemConcurso" collection
 * @method Item                setId()            Sets the current record's "id" value
 * @method Item                setNombreItem()    Sets the current record's "nombre_item" value
 * @method Item                setAcronimo()      Sets the current record's "acronimo" value
 * @method Item                setTieneSubitem()  Sets the current record's "tiene_subitem" value
 * @method Item                setConcursos()     Sets the current record's "Concursos" collection
 * @method Item                setSubitems()      Sets the current record's "Subitems" collection
 * @method Item                setItemConcurso()  Sets the current record's "ItemConcurso" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre_item', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('acronimo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tiene_subitem', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Concurso as Concursos', array(
             'refClass' => 'ItemConcurso',
             'local' => 'item_id',
             'foreign' => 'concurso_id'));

        $this->hasMany('Subitem as Subitems', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $this->hasMany('ItemConcurso', array(
             'local' => 'id',
             'foreign' => 'item_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}