<?php

/**
 * BasePersonaSistema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $perfil
 * @property integer $rut
 * @property string $dv
 * @property string $nombre
 * @property string $apellido1
 * @property string $apellido2
 * @property string $telefono
 * @property string $email
 * @property string $password
 * @property string $token_recuperar_password
 * @property Doctrine_Collection $Evaluaciones
 * 
 * @method integer             getId()                       Returns the current record's "id" value
 * @method integer             getPerfil()                   Returns the current record's "perfil" value
 * @method integer             getRut()                      Returns the current record's "rut" value
 * @method string              getDv()                       Returns the current record's "dv" value
 * @method string              getNombre()                   Returns the current record's "nombre" value
 * @method string              getApellido1()                Returns the current record's "apellido1" value
 * @method string              getApellido2()                Returns the current record's "apellido2" value
 * @method string              getTelefono()                 Returns the current record's "telefono" value
 * @method string              getEmail()                    Returns the current record's "email" value
 * @method string              getPassword()                 Returns the current record's "password" value
 * @method string              getTokenRecuperarPassword()   Returns the current record's "token_recuperar_password" value
 * @method Doctrine_Collection getEvaluaciones()             Returns the current record's "Evaluaciones" collection
 * @method PersonaSistema      setId()                       Sets the current record's "id" value
 * @method PersonaSistema      setPerfil()                   Sets the current record's "perfil" value
 * @method PersonaSistema      setRut()                      Sets the current record's "rut" value
 * @method PersonaSistema      setDv()                       Sets the current record's "dv" value
 * @method PersonaSistema      setNombre()                   Sets the current record's "nombre" value
 * @method PersonaSistema      setApellido1()                Sets the current record's "apellido1" value
 * @method PersonaSistema      setApellido2()                Sets the current record's "apellido2" value
 * @method PersonaSistema      setTelefono()                 Sets the current record's "telefono" value
 * @method PersonaSistema      setEmail()                    Sets the current record's "email" value
 * @method PersonaSistema      setPassword()                 Sets the current record's "password" value
 * @method PersonaSistema      setTokenRecuperarPassword()   Sets the current record's "token_recuperar_password" value
 * @method PersonaSistema      setEvaluaciones()             Sets the current record's "Evaluaciones" collection
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersonaSistema extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('persona_sistema');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('perfil', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 2,
             ));
        $this->hasColumn('rut', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('dv', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('apellido1', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('apellido2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('telefono', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('token_recuperar_password', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Evaluacion as Evaluaciones', array(
             'local' => 'id',
             'foreign' => 'persona_sistema_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}