<?php

/**
 * BaseDivulgacionDePersona
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $persona_id
 * @property string $texto_divulgacion
 * @property Persona $Persona
 * 
 * @method integer              getId()                Returns the current record's "id" value
 * @method integer              getPersonaId()         Returns the current record's "persona_id" value
 * @method string               getTextoDivulgacion()  Returns the current record's "texto_divulgacion" value
 * @method Persona              getPersona()           Returns the current record's "Persona" value
 * @method DivulgacionDePersona setId()                Sets the current record's "id" value
 * @method DivulgacionDePersona setPersonaId()         Sets the current record's "persona_id" value
 * @method DivulgacionDePersona setTextoDivulgacion()  Sets the current record's "texto_divulgacion" value
 * @method DivulgacionDePersona setPersona()           Sets the current record's "Persona" value
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDivulgacionDePersona extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('divulgacion_de_persona');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('persona_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('texto_divulgacion', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Persona', array(
             'local' => 'persona_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}