<?php

/**
 * AjusteDetalleRecursoGastosOperacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AjusteDetalleRecursoGastosOperacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AjusteDetalleRecursoGastosOperacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AjusteDetalleRecursoGastosOperacion');
    }
}