<?php

/**
 * AjusteDetalleRecursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AjusteDetalleRecursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AjusteDetalleRecursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AjusteDetalleRecurso');
    }
}