<?php

/**
 * AlternativaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlternativaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlternativaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Alternativa');
    }
}