<?php

/**
 * ArchivoDePersonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchivoDePersonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArchivoDePersonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArchivoDePersona');
    }
}