<?php

/**
 * ArchivoRecursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchivoRecursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArchivoRecursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArchivoRecurso');
    }
}