<?php

/**
 * CapituloLibroDePersonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CapituloLibroDePersonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CapituloLibroDePersonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CapituloLibroDePersona');
    }
}