<?php

/**
 * CompromisoDeConvenioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompromisoDeConvenioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompromisoDeConvenioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompromisoDeConvenio');
    }
}