<?php

/**
 * CompromisoDeConcursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompromisoDeConcursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompromisoDeConcursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompromisoDeConcurso');
    }
}