<?php

/**
 * ConcursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConcursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConcursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Concurso');
    }
    
    public static function findOneByAcronimo($acronimo){
      $concursos = Doctrine_Core::getTable('Concurso')->findByAcronimo($acronimo);
      $hoy = date("Y-m-d H:i:s");
      $hoy_date = strtotime($hoy);
      
      foreach($concursos as $c){
        if(strtotime($c->getInicioPostulacion()) <= $hoy_date && strtotime($c->getTerminoPostulacion()) >= $hoy_date ){
          return $c;
        }
      }
    }
}
