<?php

/**
 * ConcursoTipoArchivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConcursoTipoArchivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConcursoTipoArchivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConcursoTipoArchivo');
    }
}