<?php

/**
 * ConvocatoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConvocatoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConvocatoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Convocatoria');
    }
    
    public static function getPostulacionesAprobadasByAnioConvocatoria($anio){
      $query = Doctrine_Core::getTable('PersonaConcurso')
          ->createQuery('persona_concurso')
          ->select()
          ->leftJoin('persona_concurso.ParticipantePostulacion participante_postulacion')
          ->leftJoin('participante_postulacion.Persona persona')
          ->leftJoin('persona_concurso.Concurso concurso')
          ->leftJoin('concurso.Convocatoria convocatoria')
          ->leftJoin('persona.UnidadAcademica unidad_academica')
          ->leftJoin('unidad_academica.Facultad facultad')
          ->where('persona_concurso.estado = 2 AND participante_postulacion.tipo_participante = 1 AND persona_concurso.esta_aprobado = 1 AND convocatoria.anio = ?',array($anio))
          ->orderBy('facultad.orden, unidad_academica.nombre, concurso.nombre_concurso, persona.apellido1 ASC');
          
          return $query->execute();
          
          
    }
}
