<?php

/**
 * DetalleRecursoGastosOperacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleRecursoGastosOperacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleRecursoGastosOperacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleRecursoGastosOperacion');
    }
}