<?php

/**
 * DetalleRecursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleRecursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleRecursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleRecurso');
    }
}