<?php

/**
 * DivulgacionDePersonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DivulgacionDePersonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DivulgacionDePersonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DivulgacionDePersona');
    }
}