<?php

/**
 * DoctoradoAcreditadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DoctoradoAcreditadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DoctoradoAcreditadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DoctoradoAcreditado');
    }
}