<?php

/**
 * FacultadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacultadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacultadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Facultad');
    }
}