<?php

/**
 * ItemConcursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemConcursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ItemConcursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ItemConcurso');
    }
}