<?php

/**
 * LibroDePersonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LibroDePersonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LibroDePersonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LibroDePersona');
    }
}