<?php

/**
 * NotaProductividadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaProductividadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaProductividadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaProductividad');
    }
}