<?php

/**
 * NotaFormulacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaFormulacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaFormulacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaFormulacion');
    }
}