<?php

/**
 * ObraDePersonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObraDePersonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObraDePersonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ObraDePersona');
    }
}