<?php

/**
 * ParticipanteExternoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParticipanteExternoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParticipanteExternoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ParticipanteExterno');
    }
}