<?php

/**
 * ParticipantePostulacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParticipantePostulacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParticipantePostulacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ParticipantePostulacion');
    }
}