<?php

/**
 * PersonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Persona');
    }
    
    public function getProyectosFondecytValidados($persona_id, $anio){
      return Doctrine_Query::create()
        ->from('ProyectoDePersona p')
        ->where('p.persona_id = ? AND p.tipo_proyecto = ?', array($persona_id, 2))
        ->execute();
    }
    
    public static function getPublicacionesISIValidadasDesdeAnio($persona_id,$anio){
      return Doctrine_Query::create()
        ->from('PublicacionDePersona p')
        ->where('p.persona_id = ? AND p.es_isi = ? AND p.anio >= ? AND p.tipo_publicacion = ?', array($persona_id, 1, $anio, 'ISI WoS'))
        ->execute();
    }
    
    public static function getPublicacionesScieloDesdeAnio($persona_id,$anio){
      return Doctrine_Query::create()
        ->from('PublicacionDePersona p')
        ->where('p.persona_id = ? AND p.anio >= ? AND p.tipo_publicacion = ?', array($persona_id, $anio, 'SciELO'))
        ->execute();
    }
    
    public static function login($rut,$dv){
    	return Doctrine_Query::create()
    	->from('Persona p')
    	->where('p.rut = ?', array($rut))
    	->andWhere('p.dv = ?', array($dv))
    	->fetchOne();    	
    }
    
    public static function buscarPorNombreOApellido1OApellido2($nombre = '', $apellido1 = '', $apellido2 = ''){
    	return Doctrine_Query::create()
    	->from('Persona p')
    	->where('p.nombre LIKE ? AND p.apellido1 LIKE ? AND p.apellido2 LIKE ?', array('%'.$nombre.'%', '%'.$apellido1.'%', '%'.$apellido2.'%'))
    	->execute();
    }
}
