<?php

/**
 * PersonaConcursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonaConcursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonaConcursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonaConcurso');
    }
    
    public function getDirector($persona_concurso_id){
    	return Doctrine_Query::create()
    	->from('ParticipantePostulacion pp')
    	->where('pp.persona_concurso_id = ? and pp.tipo_participante = ?',array($persona_concurso_id, 1))
    	->fetchOne();
    }
    
    public function getPostulacionesEnviadasYEsperandoEvaluacionRecursos(Doctrine_Query $query){ //estado_evaluacion == 2 espera evaluación de recursos
      $query->Where('estado_evaluacion = ?', array(2));
    }
    
    public function getPostulacionesEnviadasYEsperandoEvaluacion(Doctrine_Query $query){
      $query->Where('(estado_evaluacion = ? OR estado_evaluacion = ?) AND estado = ?', array(0,1,2)); // Evaluaciones sin ninguna evaluación o con al menos una evaluación
      
      return $query;
    }
    
    public static function getEvaluacionesEnviadas($id_persona_concurso){
      return Doctrine_Query::create()
        ->from('Evaluacion e')
        ->where('persona_concurso_id = ? AND estado = ?', array($id_persona_concurso, 2))
        ->execute();
    }
    
    public function getPostulacionesEsperandoEvaluacionFinal(Doctrine_Query $query){ // estado_evaluacion == 3 espera evaluación final
      $query->where('estado_evaluacion = ?',array(3));
      
      return $query;
    }
}
