<?php

/**
 * PersonaSistemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonaSistemaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonaSistemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonaSistema');
    }
}