<?php

/**
 * PersonaSistema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Miguel Alcaino
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PersonaSistema extends BasePersonaSistema
{
  public function setPassword($v){
        if($v != ''){
            $this->_set('password',md5($v));
        }
    }
  public function __toString(){
        return $this->getNombre().' '.$this->getApellido1().' '.$this->getApellido2();
  }
}
