<?php

/**
 * PersonaExternaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonaExternaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonaExternaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonaExterna');
    }
}