<?php

/**
 * PorcentajeProductividadConcursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PorcentajeProductividadConcursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PorcentajeProductividadConcursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PorcentajeProductividadConcurso');
    }
}