<?php

/**
 * PorcentajeEvaluacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PorcentajeEvaluacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PorcentajeEvaluacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PorcentajeEvaluacion');
    }
}