<?php

/**
 * PreguntaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreguntaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreguntaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pregunta');
    }
}