<?php

/**
 * ProyectoDePersonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProyectoDePersonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProyectoDePersonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProyectoDePersona');
    }
}