<?php

/**
 * PublicacionDePersonaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicacionDePersonaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PublicacionDePersonaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PublicacionDePersona');
    }
}