<?php

/**
 * Recurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Recurso extends BaseRecurso
{
	public function __toString(){
		return $this->getItemConcurso()->getItem()->getNombreItem();
	}
	
	public function excedePorcentaje(){
	  $suma = 0;
	  foreach($this->getPersonaConcurso()->getRecursos() as $recurso){
	    $suma = $suma + $recurso->getTotal();
	  }
	  
	  //Excepción para Tesis con su 33%
	  if($this->getPersonaConcurso()->getConcurso()->getAcronimo() == 'di_apoyo_tesis_doctoral' && $this->getItemConcurso()->getItem()->getAcronimo() == 'viajes_y_viaticos'){
	  if($this->getTotal() > $this->getItemConcurso()->getMontoMaximo()){
	    return true;
	  }else{
	    return false;
	  }
	  }
	  
	  if( $this->getTotal() > (($this->getItemConcurso()->getPorcentajeMaximo()/100)*$suma) ){
	    return true;
	  }else{
	    return false;
	  }
	}
}
