<?php

/**
 * RespuestaAlternativaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RespuestaAlternativaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RespuestaAlternativaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RespuestaAlternativa');
    }
}