<?php

/**
 * RestriccionConcursoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RestriccionConcursoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RestriccionConcursoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RestriccionConcurso');
    }
}