<?php

/**
 * SubitemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubitemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubitemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subitem');
    }
}