<?php

/**
 * TesistaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TesistaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TesistaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tesista');
    }
}