<?php

/**
 * TipoArchivoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoArchivoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoArchivoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoArchivo');
    }
}