<?php

/**
 * TipoProfesor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    postulacion_interna
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TipoProfesor extends BaseTipoProfesor
{
	public function __toString(){
		return $this->getTipo();
	}
}