<?php

/**
 * TipoProfesorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoProfesorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoProfesorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoProfesor');
    }
}