<?php

/**
 * UnidadAcademicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnidadAcademicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnidadAcademicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnidadAcademica');
    }
}